### ISSUE TITLE
What timeframe is the data?

### ISSUE THREAD

**Issue by broakenmedia** [NikhilBhutani/EasyDataAnalyzer#1]
Sorry if i'm misunderstanding but when is the data calculated for? "all-time", "current-session", "last hour" etc?

**Comment by NikhilBhutani** [comment]
The api used in this library triggers a reset counter after your device is switched off, you can use your own way to store the data in local/remote database according to your requirements for the time frame.
Hope this helps.

**Comment by broakenmedia** [comment]
@NikhilBhutani Great, thank you!
